version: "3.4"

services:
    api:
        build: IncomeMonitor.WebUI
        ports:
          - "8080:80"
        depends_on:
          - db

    db:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        ports:
          - "1433:1433"


